augs_conf:
  - name: impulse_response
    args:
      root: /mnt/SadaHati/Home/SE/FINALLY-Speech-Enhancement/datasets/micro_ir
      ir_files_path:
        train: "/mnt/SadaHati/Home/SE/FINALLY-Speech-Enhancement/datasets/metadata/micro_ir/train_files.txt"
        val: "/mnt/SadaHati/Home/SE/FINALLY-Speech-Enhancement/datasets/metadata/micro_ir/val_files.txt"
      prob: 0.4

  - name: impulse_response
    args:
      root: /mnt/SadaHati/Home/SE/FINALLY-Speech-Enhancement/datasets/DNS_ir/datasets_fullband/impulse_responses/SLR26/simulated_rirs_48k
      ir_files_path:
        train: "/mnt/SadaHati/Home/SE/FINALLY-Speech-Enhancement/datasets/metadata/DNS_ir/train_files.txt"
        val: "/mnt/SadaHati/Home/SE/FINALLY-Speech-Enhancement/datasets/metadata/DNS_ir/val_files.txt"
      prob: 0.6

  - name: noise
    args:
      root: /mnt/SadaHati/Home/SE/FINALLY-Speech-Enhancement/datasets/DNS_noise/datasets_fullband/Testing
      noise_files_path:
        train: "/mnt/SadaHati/Home/SE/FINALLY-Speech-Enhancement/datasets/metadata/DNS_noise/testing.txt"
        val: "/mnt/SadaHati/Home/SE/FINALLY-Speech-Enhancement/datasets/metadata/DNS_noise/val_files.txt"
      prob: 0.95

  # - name: acrusher
  #   args:
  #     prob: 0.25

  # - name: crystalizer
  #   args:
  #     prob: 0.4

  # - name: vibrato
  #   args:
  #     prob: 0.15

  # - name: flanger
  #   args:
  #     prob: 0.15

  - name: codec
    args:
      prob: 0.5
